// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "InitiateSignal.pb.h"
// @@protoc_insertion_point(imports)

@implementation InitiateSignalRoot
static PBExtensionRegistry *extensionRegistry = nil;
+ (PBExtensionRegistry *)extensionRegistry {
    return extensionRegistry;
}

+ (void)initialize {
    if (self == [InitiateSignalRoot class]) {
        PBMutableExtensionRegistry *registry = [PBMutableExtensionRegistry registry];
        [self registerAllExtensions:registry];
        extensionRegistry = registry;
    }
}
+ (void)registerAllExtensions:(PBMutableExtensionRegistry *)registry {
}
@end

@interface InitiateSignal ()
@property (strong) NSString *initiator;
@property UInt64 sessionId;
@property UInt32 port;
@property (strong) NSString *serverName;
@property UInt32 version;
@end

@implementation InitiateSignal

- (BOOL)hasInitiator {
    return !!hasInitiator_;
}
- (void)setHasInitiator:(BOOL)value_ {
    hasInitiator_ = !!value_;
}
@synthesize initiator;
- (BOOL)hasSessionId {
    return !!hasSessionId_;
}
- (void)setHasSessionId:(BOOL)value_ {
    hasSessionId_ = !!value_;
}
@synthesize sessionId;
- (BOOL)hasPort {
    return !!hasPort_;
}
- (void)setHasPort:(BOOL)value_ {
    hasPort_ = !!value_;
}
@synthesize port;
- (BOOL)hasServerName {
    return !!hasServerName_;
}
- (void)setHasServerName:(BOOL)value_ {
    hasServerName_ = !!value_;
}
@synthesize serverName;
- (BOOL)hasVersion {
    return !!hasVersion_;
}
- (void)setHasVersion:(BOOL)value_ {
    hasVersion_ = !!value_;
}
@synthesize version;
- (id)init {
    if ((self = [super init])) {
        self.initiator  = @"";
        self.sessionId  = 0L;
        self.port       = 0;
        self.serverName = @"";
        self.version    = 0;
    }
    return self;
}
static InitiateSignal *defaultInitiateSignalInstance = nil;
+ (void)initialize {
    if (self == [InitiateSignal class]) {
        defaultInitiateSignalInstance = [[InitiateSignal alloc] init];
    }
}
+ (InitiateSignal *)defaultInstance {
    return defaultInitiateSignalInstance;
}
- (InitiateSignal *)defaultInstance {
    return defaultInitiateSignalInstance;
}
- (BOOL)isInitialized {
    return YES;
}
- (void)writeToCodedOutputStream:(PBCodedOutputStream *)output {
    if (self.hasInitiator) {
        [output writeString:1 value:self.initiator];
    }
    if (self.hasSessionId) {
        [output writeUInt64:2 value:self.sessionId];
    }
    if (self.hasPort) {
        [output writeUInt32:3 value:self.port];
    }
    if (self.hasServerName) {
        [output writeString:4 value:self.serverName];
    }
    if (self.hasVersion) {
        [output writeUInt32:5 value:self.version];
    }
    [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32)serializedSize {
    __block SInt32 size_ = memoizedSerializedSize;
    if (size_ != -1) {
        return size_;
    }

    size_ = 0;
    if (self.hasInitiator) {
        size_ += computeStringSize(1, self.initiator);
    }
    if (self.hasSessionId) {
        size_ += computeUInt64Size(2, self.sessionId);
    }
    if (self.hasPort) {
        size_ += computeUInt32Size(3, self.port);
    }
    if (self.hasServerName) {
        size_ += computeStringSize(4, self.serverName);
    }
    if (self.hasVersion) {
        size_ += computeUInt32Size(5, self.version);
    }
    size_ += self.unknownFields.serializedSize;
    memoizedSerializedSize = size_;
    return size_;
}
+ (InitiateSignal *)parseFromData:(NSData *)data {
    return (InitiateSignal *)[[[InitiateSignal builder] mergeFromData:data] build];
}
+ (InitiateSignal *)parseFromData:(NSData *)data extensionRegistry:(PBExtensionRegistry *)extensionRegistry {
    return (InitiateSignal *)[[[InitiateSignal builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (InitiateSignal *)parseFromInputStream:(NSInputStream *)input {
    return (InitiateSignal *)[[[InitiateSignal builder] mergeFromInputStream:input] build];
}
+ (InitiateSignal *)parseFromInputStream:(NSInputStream *)input
                       extensionRegistry:(PBExtensionRegistry *)extensionRegistry {
    return (InitiateSignal *)[[[InitiateSignal builder] mergeFromInputStream:input extensionRegistry:extensionRegistry]
        build];
}
+ (InitiateSignal *)parseFromCodedInputStream:(PBCodedInputStream *)input {
    return (InitiateSignal *)[[[InitiateSignal builder] mergeFromCodedInputStream:input] build];
}
+ (InitiateSignal *)parseFromCodedInputStream:(PBCodedInputStream *)input
                            extensionRegistry:(PBExtensionRegistry *)extensionRegistry {
    return (InitiateSignal *)[
        [[InitiateSignal builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (InitiateSignalBuilder *)builder {
    return [[InitiateSignalBuilder alloc] init];
}
+ (InitiateSignalBuilder *)builderWithPrototype:(InitiateSignal *)prototype {
    return [[InitiateSignal builder] mergeFrom:prototype];
}
- (InitiateSignalBuilder *)builder {
    return [InitiateSignal builder];
}
- (InitiateSignalBuilder *)toBuilder {
    return [InitiateSignal builderWithPrototype:self];
}
- (void)writeDescriptionTo:(NSMutableString *)output withIndent:(NSString *)indent {
    if (self.hasInitiator) {
        [output appendFormat:@"%@%@: %@\n", indent, @"initiator", self.initiator];
    }
    if (self.hasSessionId) {
        [output appendFormat:@"%@%@: %@\n", indent, @"sessionId", [NSNumber numberWithLongLong:self.sessionId]];
    }
    if (self.hasPort) {
        [output appendFormat:@"%@%@: %@\n", indent, @"port", [NSNumber numberWithInteger:self.port]];
    }
    if (self.hasServerName) {
        [output appendFormat:@"%@%@: %@\n", indent, @"serverName", self.serverName];
    }
    if (self.hasVersion) {
        [output appendFormat:@"%@%@: %@\n", indent, @"version", [NSNumber numberWithInteger:self.version]];
    }
    [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL)isEqual:(id)other {
    if (other == self) {
        return YES;
    }
    if (![other isKindOfClass:[InitiateSignal class]]) {
        return NO;
    }
    InitiateSignal *otherMessage = other;
    return self.hasInitiator == otherMessage.hasInitiator &&
           (!self.hasInitiator || [self.initiator isEqual:otherMessage.initiator]) &&
           self.hasSessionId == otherMessage.hasSessionId &&
           (!self.hasSessionId || self.sessionId == otherMessage.sessionId) && self.hasPort == otherMessage.hasPort &&
           (!self.hasPort || self.port == otherMessage.port) && self.hasServerName == otherMessage.hasServerName &&
           (!self.hasServerName || [self.serverName isEqual:otherMessage.serverName]) &&
           self.hasVersion == otherMessage.hasVersion && (!self.hasVersion || self.version == otherMessage.version) &&
           (self.unknownFields == otherMessage.unknownFields ||
            (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger)hash {
    __block NSUInteger hashCode = 7;
    if (self.hasInitiator) {
        hashCode = hashCode * 31 + [self.initiator hash];
    }
    if (self.hasSessionId) {
        hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.sessionId] hash];
    }
    if (self.hasPort) {
        hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.port] hash];
    }
    if (self.hasServerName) {
        hashCode = hashCode * 31 + [self.serverName hash];
    }
    if (self.hasVersion) {
        hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.version] hash];
    }
    hashCode = hashCode * 31 + [self.unknownFields hash];
    return hashCode;
}
@end

@interface InitiateSignalBuilder ()
@property (strong) InitiateSignal *result;
@end

@implementation InitiateSignalBuilder
@synthesize result;
- (id)init {
    if ((self = [super init])) {
        self.result = [[InitiateSignal alloc] init];
    }
    return self;
}
- (PBGeneratedMessage *)internalGetResult {
    return result;
}
- (InitiateSignalBuilder *)clear {
    self.result = [[InitiateSignal alloc] init];
    return self;
}
- (InitiateSignalBuilder *)clone {
    return [InitiateSignal builderWithPrototype:result];
}
- (InitiateSignal *)defaultInstance {
    return [InitiateSignal defaultInstance];
}
- (InitiateSignal *)build {
    [self checkInitialized];
    return [self buildPartial];
}
- (InitiateSignal *)buildPartial {
    InitiateSignal *returnMe = result;
    self.result              = nil;
    return returnMe;
}
- (InitiateSignalBuilder *)mergeFrom:(InitiateSignal *)other {
    if (other == [InitiateSignal defaultInstance]) {
        return self;
    }
    if (other.hasInitiator) {
        [self setInitiator:other.initiator];
    }
    if (other.hasSessionId) {
        [self setSessionId:other.sessionId];
    }
    if (other.hasPort) {
        [self setPort:other.port];
    }
    if (other.hasServerName) {
        [self setServerName:other.serverName];
    }
    if (other.hasVersion) {
        [self setVersion:other.version];
    }
    [self mergeUnknownFields:other.unknownFields];
    return self;
}
- (InitiateSignalBuilder *)mergeFromCodedInputStream:(PBCodedInputStream *)input {
    return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (InitiateSignalBuilder *)mergeFromCodedInputStream:(PBCodedInputStream *)input
                                   extensionRegistry:(PBExtensionRegistry *)extensionRegistry {
    PBUnknownFieldSetBuilder *unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
    while (YES) {
        SInt32 tag = [input readTag];
        switch (tag) {
            case 0:
                [self setUnknownFields:[unknownFields build]];
                return self;
            default: {
                if (![self parseUnknownField:input
                               unknownFields:unknownFields
                           extensionRegistry:extensionRegistry
                                         tag:tag]) {
                    [self setUnknownFields:[unknownFields build]];
                    return self;
                }
                break;
            }
            case 10: {
                [self setInitiator:[input readString]];
                break;
            }
            case 16: {
                [self setSessionId:[input readUInt64]];
                break;
            }
            case 24: {
                [self setPort:[input readUInt32]];
                break;
            }
            case 34: {
                [self setServerName:[input readString]];
                break;
            }
            case 40: {
                [self setVersion:[input readUInt32]];
                break;
            }
        }
    }
}
- (BOOL)hasInitiator {
    return result.hasInitiator;
}
- (NSString *)initiator {
    return result.initiator;
}
- (InitiateSignalBuilder *)setInitiator:(NSString *)value {
    result.hasInitiator = YES;
    result.initiator    = value;
    return self;
}
- (InitiateSignalBuilder *)clearInitiator {
    result.hasInitiator = NO;
    result.initiator    = @"";
    return self;
}
- (BOOL)hasSessionId {
    return result.hasSessionId;
}
- (UInt64)sessionId {
    return result.sessionId;
}
- (InitiateSignalBuilder *)setSessionId:(UInt64)value {
    result.hasSessionId = YES;
    result.sessionId    = value;
    return self;
}
- (InitiateSignalBuilder *)clearSessionId {
    result.hasSessionId = NO;
    result.sessionId    = 0L;
    return self;
}
- (BOOL)hasPort {
    return result.hasPort;
}
- (UInt32)port {
    return result.port;
}
- (InitiateSignalBuilder *)setPort:(UInt32)value {
    result.hasPort = YES;
    result.port    = value;
    return self;
}
- (InitiateSignalBuilder *)clearPort {
    result.hasPort = NO;
    result.port    = 0;
    return self;
}
- (BOOL)hasServerName {
    return result.hasServerName;
}
- (NSString *)serverName {
    return result.serverName;
}
- (InitiateSignalBuilder *)setServerName:(NSString *)value {
    result.hasServerName = YES;
    result.serverName    = value;
    return self;
}
- (InitiateSignalBuilder *)clearServerName {
    result.hasServerName = NO;
    result.serverName    = @"";
    return self;
}
- (BOOL)hasVersion {
    return result.hasVersion;
}
- (UInt32)version {
    return result.version;
}
- (InitiateSignalBuilder *)setVersion:(UInt32)value {
    result.hasVersion = YES;
    result.version    = value;
    return self;
}
- (InitiateSignalBuilder *)clearVersion {
    result.hasVersion = NO;
    result.version    = 0;
    return self;
}
@end


// @@protoc_insertion_point(global_scope)
