//
//  Copyright (c) 2019 Signal. All rights reserved.
//

import Foundation

// NOTE: This file is generated by /Scripts/sds_codegen/sds_parse_swift_bridging.py.
// Do not manually edit it, instead run `sds_codegen.sh`.

@interface SPKProtoTSProtoWhisperMessage : NSObject
@end

@interface SPKProtoTSProtoPreKeyWhisperMessage : NSObject
@end

@interface SPKProtoTSProtoKeyExchangeMessage : NSObject
@end

@interface SPKProtoTSProtoSenderKeyMessage : NSObject
@end

@interface SPKProtoTSProtoSenderKeyDistributionMessage : NSObject
@end
