//
//  Copyright (c) 2019 Open Whisper Systems. All rights reserved.
//

#import "BaseModel.h"
#import "StickerInfo.h"

NS_ASSUME_NONNULL_BEGIN

@class SDSAnyReadTransaction;

@interface InstalledSticker : BaseModel

@property (nonatomic, readonly) StickerInfo *info;
@property (nonatomic, readonly, nullable) NSString *emojiString;

// Convenience accessors.
@property (nonatomic, readonly) NSData *packId;
@property (nonatomic, readonly) NSData *packKey;
@property (nonatomic, readonly) UInt32 stickerId;

- (instancetype)initWithInfo:(StickerInfo *)info emojiString:(nullable NSString *)emojiString;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`.

// clang-format off

- (instancetype)initWithUniqueId:(NSString *)uniqueId
                     emojiString:(nullable NSString *)emojiString
                            info:(StickerInfo *)info
NS_SWIFT_NAME(init(uniqueId:emojiString:info:));

// clang-format on

// --- CODE GENERATION MARKER

+ (NSString *)uniqueIdForStickerInfo:(StickerInfo *)info;

@end

NS_ASSUME_NONNULL_END
