//
//  Copyright (c) 2019 Open Whisper Systems. All rights reserved.
//

#import "StickerInfo.h"
#import "TSYapDatabaseObject.h"

NS_ASSUME_NONNULL_BEGIN

@class SDSAnyReadTransaction;

@interface KnownStickerPack : TSYapDatabaseObject

@property (nonatomic, readonly) StickerPackInfo *info;
@property (nonatomic) NSInteger referenceCount;

- (instancetype)initWithInfo:(StickerPackInfo *)info;

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run
// `sds_codegen.sh`.

// clang-format off

- (instancetype)initWithUniqueId:(NSString *)uniqueId
                            info:(StickerPackInfo *)info
                  referenceCount:(NSInteger)referenceCount
NS_SWIFT_NAME(init(uniqueId:info:referenceCount:));

// clang-format on

// --- CODE GENERATION MARKER

+ (NSString *)uniqueIdForStickerPackInfo:(StickerPackInfo *)info;

@end

NS_ASSUME_NONNULL_END
