# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

link_with 'TSKitOSXTestApp', 'TSKitOSXTestAppTests'
pod 'SignalServiceKit', :path => '../../SignalServiceKit.podspec'

target 'TSKitOSXTestApp' do

end

target 'TSKitOSXTestAppTests' do

end

