//
//  Copyright (c) 2019 Open Whisper Systems. All rights reserved.
//

#import "OWSContactQuery.h"

NS_ASSUME_NONNULL_BEGIN

@implementation OWSContactQuery

- (instancetype)initWithUniqueId:(NSString *)uniqueId lastQueried:(NSDate *)lastQueried nonce:(NSData *)nonce
{
    self = [super initWithUniqueId:uniqueId];

    if (!self) {
        return self;
    }

    _lastQueried = lastQueried;
    _nonce = nonce;

    return self;
}

// --- CODE GENERATION MARKER

// This snippet is generated by /Scripts/sds_codegen/sds_generate.py. Do not manually edit it, instead run `sds_codegen.sh`.

// clang-format off

- (instancetype)initWithGrdbId:(int64_t)grdbId
                      uniqueId:(NSString *)uniqueId
                     lastQueried:(NSDate *)lastQueried
                           nonce:(NSData *)nonce
{
    self = [super initWithGrdbId:grdbId
                        uniqueId:uniqueId];

    if (!self) {
        return self;
    }

    _lastQueried = lastQueried;
    _nonce = nonce;

    return self;
}

// clang-format on

// --- CODE GENERATION MARKER

@end

NS_ASSUME_NONNULL_END
