//
// Copyright 2024 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only
//

// Code generated by Wire protocol buffer compiler, do not edit.
// Source: BackupProto.BackupProtoGroupSelfInvitationRevokedUpdate in Backup.proto
import Foundation
import Wire

/**
 * An invitation to self was revoked.
 */
public struct BackupProtoGroupSelfInvitationRevokedUpdate {

    @ProtoDefaulted
    public var revokerAci: Foundation.Data?
    public var unknownFields: UnknownFields = .init()

    public init(configure: (inout Self) -> Swift.Void = { _ in }) {
        configure(&self)
    }

}

#if !WIRE_REMOVE_EQUATABLE
extension BackupProtoGroupSelfInvitationRevokedUpdate : Equatable {
}
#endif

#if !WIRE_REMOVE_HASHABLE
extension BackupProtoGroupSelfInvitationRevokedUpdate : Hashable {
}
#endif

extension BackupProtoGroupSelfInvitationRevokedUpdate : Sendable {
}

extension BackupProtoGroupSelfInvitationRevokedUpdate : ProtoDefaultedValue {

    public static var defaultedValue: BackupProtoGroupSelfInvitationRevokedUpdate {
        BackupProtoGroupSelfInvitationRevokedUpdate()
    }
}

extension BackupProtoGroupSelfInvitationRevokedUpdate : ProtoMessage {

    public static func protoMessageTypeURL() -> String {
        return "type.googleapis.com/BackupProto.BackupProtoGroupSelfInvitationRevokedUpdate"
    }

}

extension BackupProtoGroupSelfInvitationRevokedUpdate : Proto3Codable {

    public init(from protoReader: ProtoReader) throws {
        var revokerAci: Foundation.Data? = nil

        let token = try protoReader.beginMessage()
        while let tag = try protoReader.nextTag(token: token) {
            switch tag {
            case 1: revokerAci = try protoReader.decode(Foundation.Data.self)
            default: try protoReader.readUnknownField(tag: tag)
            }
        }
        self.unknownFields = try protoReader.endMessage(token: token)

        self._revokerAci.wrappedValue = revokerAci
    }

    public func encode(to protoWriter: ProtoWriter) throws {
        try protoWriter.encode(tag: 1, value: self.revokerAci)
        try protoWriter.writeUnknownFields(unknownFields)
    }

}

#if !WIRE_REMOVE_CODABLE
extension BackupProtoGroupSelfInvitationRevokedUpdate : Codable {

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringLiteralCodingKeys.self)
        self._revokerAci.wrappedValue = try container.decodeIfPresent(stringEncoded: Foundation.Data.self, forKey: "revokerAci")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringLiteralCodingKeys.self)

        try container.encodeIfPresent(stringEncoded: self.revokerAci, forKey: "revokerAci")
    }

}
#endif
