//
//  Copyright (c) 2019 Signal. All rights reserved.
//

import Foundation

// NOTE: This file is generated by /Scripts/sds_codegen/sds_parse_swift_bridging.py.
// Do not manually edit it, instead run `sds_codegen.sh`.

@interface OWSSwiftUtils : NSObject
@end

@interface OWSDataParser : NSObject
@end

@interface Logger : NSObject
@end
