platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'TSKitiOSTestApp' do
  pod 'SocketRocket', git: 'https://github.com/facebook/SocketRocket.git'
  pod 'AxolotlKit',  git: 'https://github.com/signalapp/SignalProtocolKit.git'
  pod 'SignalServiceKit', :path => '../../../SignalServiceKit.podspec'
  pod 'OpenSSL', git: 'https://github.com/signalapp/OpenSSL-Pod'

  target 'TSKitiOSTestAppTests' do
     inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.to_s == "SignalServiceKit"
      puts "--[!] Disabling singleton enforcement for SSK."
      target.build_configurations.each do |config|
        existing_definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        if existing_definitions == nil || existing.length == 0
          existing_definitions = "$(inheritied)"
        end

		config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = "#{existing_definitions} SSK_BUILDING_FOR_TESTS=1"
		config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-DSSK_BUILDING_FOR_TESTS']
      end
    end
  end
end
