//
//  Copyright (c) 2019 Signal. All rights reserved.
//

import Foundation

// NOTE: This file is generated by /Users/matthew/code/workspace/ows/Signal-iOS-2/Scripts/sds_codegen/sds_parse_swift_bridging.py.
// Do not manually edit it, instead run `sds_codegen.sh`.

@protocol ConversationSearchControllerDelegate
@end

@protocol SearchResultsBarDelegate
@end

@protocol MessageActionsDelegate
@end

@protocol OWSCompareSafetyNumbersActivityDelegate
@end

@protocol MessageDetailViewDelegate
@end

@protocol ContactShareViewHelperDelegate
@end

@protocol MediaTileViewControllerDelegate
@end

@protocol MenuActionsViewControllerDelegate
@end

@protocol MenuActionSheetDelegate
@end

@protocol MenuActionViewDelegate
@end

@protocol LongTextViewDelegate
@end

@protocol ColorViewDelegate
@end

@protocol ColorPickerDelegate
@end

@protocol ColorPickerViewDelegate
@end

@protocol MediaGalleryDataSource
@end

@protocol MediaGalleryDataSourceDelegate
@end

@protocol ContactsPickerDelegate
@end

@protocol GifPickerViewControllerDelegate
@end

@protocol GifPickerLayoutDelegate
@end

@protocol OnboardingCodeViewTextFieldDelegate
@end

@protocol OnboardingCodeViewDelegate
@end

@protocol ConversationHeaderViewDelegate
@end

@protocol ConversationSearchViewDelegate
@end

@protocol CallVideoHintViewDelegate
@end

@protocol ImagePickerGridControllerDelegate
@end

@protocol TitleViewDelegate
@end

@protocol PhotoCaptureDelegate
@end

@protocol CaptureOutputDelegate
@end

@protocol ImageCaptureOutput
@end

@protocol OWSPhotoCaptureViewControllerDelegate
@end

@protocol CaptureButtonDelegate
@end

@protocol SendMediaNavDelegate
@end

@protocol DoneButtonDelegate
@end

@protocol PhotoCollectionPickerDelegate
@end

@protocol PhotoLibraryDelegate
@end

@protocol CallServiceObserver
@end

@protocol SignalCallDataDelegate
@end

@protocol CallAudioServiceDelegate
@end

@protocol PeerConnectionClientDelegate
@end

@protocol VideoCaptureSettingsDelegate
@end

@protocol CallObserver
@end

@protocol CallUIAdaptee
@end

@protocol SelectionHapticFeedbackAdapter
@end

@protocol NotificationHapticFeedbackAdapter
@end

@protocol NotificationPresenterAdaptee
@end

@protocol LinkPreviewState
@end

@protocol LinkPreviewViewDraftDelegate
@end

@protocol CaptionContainerViewDelegate
@end

@protocol QuotedReplyPreviewDelegate
@end

@protocol PhotoGridItem
@end

@protocol MarqueeStep
@end

@protocol DismissInputBarDelegate
@end

@interface PhoneNumberValidatorTest : NSObject
@end

@interface ContactDiscoveryOperationTest : NSObject
@end

@interface ContactsPickerTest : NSObject
@end

@interface FullTextSearcherContactsManager : NSObject
@end

@interface FullTextSearcherTest : NSObject
@end

@interface SearcherTest : NSObject
@end

@interface DisplayableTextTest : NSObject
@end

@interface ByteParserTest : NSObject
@end

@interface StringAdditionsTest : NSObject
@end

@interface ImageCacheTest : NSObject
@end

@interface ParamParserTest : NSObject
@end

@interface SSKProtoEnvelopeTest : NSObject
@end

@interface FailingTSAccountManager : NSObject
@end

@interface VerifyingTSAccountManager : NSObject
@end

@interface TokenObtainingTSAccountManager : NSObject
@end

@interface VerifyingPushRegistrationManager : NSObject
@end

@interface AccountManagerTest : NSObject
@end

@interface MantlePerfTest : NSObject
@end

@interface FakePeerConnectionClientDelegate : NSObject
@end

@interface PeerConnectionClientTest : NSObject
@end

@interface ImageEditorModelTest : NSObject
@end

@interface ImageEditorTest : NSObject
@end

@interface ConversationSearchController : NSObject
@end

@interface SearchResultsBar : NSObject
@end

@interface WebRTCProtoConnected : NSObject
@end

@interface WebRTCProtoHangup : NSObject
@end

@interface WebRTCProtoVideoStreamingStatus : NSObject
@end

@interface WebRTCProtoData : NSObject
@end

@interface TextFieldHelper : NSObject
@end

@interface AppUpdateNag : NSObject
@end

@interface AppStoreVersionService : NSObject
@end

@interface OWSBackupLazyRestore : NSObject
@end

@interface OWSBackupAPI : NSObject
@end

@interface GiphyDownloader : NSObject
@end

@interface GiphyRendition : NSObject
@end

@interface GiphyImageInfo : NSObject
@end

@interface GiphyAPI : NSObject
@end

@interface PhoneNumberValidator : NSObject
@end

@interface AccountManager : NSObject
@end

@interface ConversationViewItemActions : NSObject
@end

@interface OWSCompareSafetyNumbersActivity : NSObject
@end

@interface OWS2FAReminderViewController : NSObject
@end

@interface MessageDetailViewController : NSObject
@end

@interface ContactShareViewHelper : NSObject
@end

@interface MediaTileViewController : NSObject
@end

@interface MediaTileViewLayout : NSObject
@end

@interface MediaGallerySectionHeader : NSObject
@end

@interface MediaGalleryStaticHeader : NSObject
@end

@interface GalleryGridCellItem : NSObject
@end

@interface GalleryItemBox : NSObject
@end

@interface Box : NSObject
@end

@interface MediaPageViewController : NSObject
@end

@interface MenuAction : NSObject
@end

@interface MenuActionsViewController : NSObject
@end

@interface MenuActionSheetView : NSObject
@end

@interface MenuActionView : NSObject
@end

@interface LongTextViewController : NSObject
@end

@interface CropScaleImageViewController : NSObject
@end

@interface IntroducingCustomNotificationAudioExperienceUpgradeViewController : NSObject
@end

@interface IntroductingReadReceiptsExperienceUpgradeViewController : NSObject
@end

@interface IntroductingTypingIndicatorsExperienceUpgradeViewController : NSObject
@end

@interface IntroducingLinkPreviewsExperienceUpgradeViewController : NSObject
@end

@interface MultiLineButton : NSObject
@end

@interface IntroductingProfilesExperienceUpgradeViewController : NSObject
@end

@interface CallKitExperienceUpgradeViewController : NSObject
@end

@interface ExperienceUpgradeViewController : NSObject
@end

@interface ExperienceUpgradesPageViewController : NSObject
@end

@interface OWSInviteFlow : NSObject
@end

@interface OWSColorPickerAccessoryView : NSObject
@end

@interface OWSCircleView : NSObject
@end

@interface ColorView : NSObject
@end

@interface OWSColorPicker : NSObject
@end

@interface ColorPickerView : NSObject
@end

@interface MockConversationViewItem : NSObject
@end

@interface MockIncomingMessage : NSObject
@end

@interface MockOutgoingMessage : NSObject
@end

@interface AddContactShareToExistingContactViewController : NSObject
@end

@interface SafetyNumberConfirmationAlert : NSObject
@end

@interface MediaGalleryAlbum : NSObject
@end

@interface MediaGalleryItem : NSObject
@end

@interface MediaGalleryNavigationController : NSObject
@end

@interface MediaGallery : NSObject
@end

@interface ContactViewController : NSObject
@end

@interface OWSImagePickerController : NSObject
@end

@interface ContactsPicker : NSObject
@end

@interface LoadingViewController : NSObject
@end

@interface GifPickerViewController : NSObject
@end

@interface GifPickerLayout : NSObject
@end

@interface GifPickerCell : NSObject
@end

@interface BackupRestoreViewController : NSObject
@end

@interface RegistrationController : NSObject
@end

@interface OnboardingCountryState : NSObject
@end

@interface OnboardingPhoneNumber : NSObject
@end

@interface OnboardingController : NSObject
@end

@interface OnboardingSplashViewController : NSObject
@end

@interface OnboardingCaptchaViewController : NSObject
@end

@interface OnboardingBaseViewController : NSObject
@end

@interface Onboarding2FAViewController : NSObject
@end

@interface OnboardingProfileViewController : NSObject
@end

@interface OnboardingCodeViewTextField : NSObject
@end

@interface OnboardingCodeView : NSObject
@end

@interface OnboardingVerificationViewController : NSObject
@end

@interface OnboardingPhoneNumberViewController : NSObject
@end

@interface OnboardingPermissionsViewController : NSObject
@end

@interface DebugUIProfile : NSObject
@end

@interface DebugUIFileBrowser : NSObject
@end

@interface DebugUINotifications : NSObject
@end

@interface DebugUICalling : NSObject
@end

@interface ConversationMessageMapping : NSObject
@end

@interface OWSTypingIndicatorInteraction : NSObject
@end

@interface ConversationHeaderView : NSObject
@end

@interface MediaDownloadView : NSObject
@end

@interface MediaUploadView : NSObject
@end

@interface OWSConversationMediaView : NSObject
@end

@interface OWSTypingIndicatorCell : NSObject
@end

@interface OWSMediaAlbumCellView : NSObject
@end

@interface MessageRecipientStatusUtils : NSObject
@end

@interface ConversationSearchViewController : NSObject
@end

@interface EmptySearchResultCell : NSObject
@end

@interface MessageStatusView : NSObject
@end

@interface CallViewController : NSObject
@end

@interface CallVideoHintView : NSObject
@end

@interface ImagePickerGridController : NSObject
@end

@interface TitleView : NSObject
@end

@interface PhotoCapture : NSObject
@end

@interface CaptureOutput : NSObject
@end

@interface PhotoCaptureOutputAdaptee : NSObject
@end

@interface StillImageCaptureOutput : NSObject
@end

@interface OWSPhotoCaptureViewController : NSObject
@end

@interface CaptureButton : NSObject
@end

@interface CapturePreviewView : NSObject
@end

@interface RecordingTimerView : NSObject
@end

@interface SendMediaNavigationController : NSObject
@end

@interface DoneButton : NSObject
@end

@interface PhotoCollectionPickerController : NSObject
@end

@interface PhotoMediaSize : NSObject
@end

@interface PhotoPickerAssetItem : NSObject
@end

@interface PhotoCollectionContents : NSObject
@end

@interface PhotoCollection : NSObject
@end

@interface PhotoLibrary : NSObject
@end

@interface OWSWebRTCCallMessageHandler : NSObject
@end

@interface SignalCallData : NSObject
@end

@interface CallService : NSObject
@end

@interface CallAudioService : NSObject
@end

@interface OutboundCallInitiator : NSObject
@end

@interface NonCallKitCallUIAdaptee : NSObject
@end

@interface PeerConnectionProxy : NSObject
@end

@interface PeerConnectionClient : NSObject
@end

@interface HardenedRTCSessionDescription : NSObject
@end

@interface VideoCaptureController : NSObject
@end

@interface SignalCall : NSObject
@end

@interface CallKitCallManager : NSObject
@end

@interface CallKitCallUIAdaptee : NSObject
@end

@interface CallUIAdapter : NSObject
@end

@interface PushRegistrationManager : NSObject
@end

@interface AppEnvironment : NSObject
@end

@interface ExperienceUpgrade : NSObject
@end

@interface ExperienceUpgradeFinder : NSObject
@end

@interface OWSLayerView : NSObject
@end

@interface SelectionHapticFeedback : NSObject
@end

@interface LegacySelectionHapticFeedbackAdapter : NSObject
@end

@interface ModernSelectionHapticFeedbackAdapter : NSObject
@end

@interface NotificationHapticFeedback : NSObject
@end

@interface ModernNotificationHapticFeedbackAdapter : NSObject
@end

@interface LegacyNotificationHapticFeedbackAdapter : NSObject
@end

@interface UserNotificationConfig : NSObject
@end

@interface UserNotificationPresenterAdaptee : NSObject
@end

@interface OWSUserNotificationActionHandler : NSObject
@end

@interface LegacyNotificationPresenterAdaptee : NSObject
@end

@interface OWSLegacyNotificationActionHandler : NSObject
@end

@interface OWSNotificationPresenter : NSObject
@end

@interface NotificationActionHandler : NSObject
@end

@interface OWSSessionResetJobQueue : NSObject
@end

@interface SessionResetOperation : NSObject
@end

@interface ConversationConfigurationSyncOperation : NSObject
@end

@interface OWSSyncPushTokensJob : NSObject
@end

@interface OWSMessageFetcherJob : NSObject
@end

@interface ReminderView : NSObject
@end

@interface LinkPreviewLoading : NSObject
@end

@interface LinkPreviewDraft : NSObject
@end

@interface LinkPreviewSent : NSObject
@end

@interface LinkPreviewImageView : NSObject
@end

@interface LinkPreviewView : NSObject
@end

@interface AudioProgressView : NSObject
@end

@interface ContactCell : NSObject
@end

@interface NeverClearView : NSObject
@end

@interface CaptionContainerView : NSObject
@end

@interface CaptionView : NSObject
@end

@interface GroupTableViewCell : NSObject
@end

@interface QuotedReplyPreview : NSObject
@end

@interface PhotoGridViewCell : NSObject
@end

@interface TypingIndicatorView : NSObject
@end

@interface MarqueeLabel : NSObject
@end

@interface GradientSetupAnimation : NSObject
@end

@interface DismissInputBar : NSObject
@end

@interface DismissableTextField : NSObject
@end

@interface VoiceMemoLockView : NSObject
@end

@interface OWSAvatarTableViewCell : NSObject
@end
