// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class OWSFingerprintProtosCombinedFingerprint;
@class OWSFingerprintProtosCombinedFingerprintBuilder;
@class OWSFingerprintProtosFingerprintData;
@class OWSFingerprintProtosFingerprintDataBuilder;
@class ObjectiveCFileOptions;
@class ObjectiveCFileOptionsBuilder;
@class PBDescriptorProto;
@class PBDescriptorProtoBuilder;
@class PBDescriptorProtoExtensionRange;
@class PBDescriptorProtoExtensionRangeBuilder;
@class PBEnumDescriptorProto;
@class PBEnumDescriptorProtoBuilder;
@class PBEnumOptions;
@class PBEnumOptionsBuilder;
@class PBEnumValueDescriptorProto;
@class PBEnumValueDescriptorProtoBuilder;
@class PBEnumValueOptions;
@class PBEnumValueOptionsBuilder;
@class PBFieldDescriptorProto;
@class PBFieldDescriptorProtoBuilder;
@class PBFieldOptions;
@class PBFieldOptionsBuilder;
@class PBFileDescriptorProto;
@class PBFileDescriptorProtoBuilder;
@class PBFileDescriptorSet;
@class PBFileDescriptorSetBuilder;
@class PBFileOptions;
@class PBFileOptionsBuilder;
@class PBMessageOptions;
@class PBMessageOptionsBuilder;
@class PBMethodDescriptorProto;
@class PBMethodDescriptorProtoBuilder;
@class PBMethodOptions;
@class PBMethodOptionsBuilder;
@class PBOneofDescriptorProto;
@class PBOneofDescriptorProtoBuilder;
@class PBServiceDescriptorProto;
@class PBServiceDescriptorProtoBuilder;
@class PBServiceOptions;
@class PBServiceOptionsBuilder;
@class PBSourceCodeInfo;
@class PBSourceCodeInfoBuilder;
@class PBSourceCodeInfoLocation;
@class PBSourceCodeInfoLocationBuilder;
@class PBUninterpretedOption;
@class PBUninterpretedOptionBuilder;
@class PBUninterpretedOptionNamePart;
@class PBUninterpretedOptionNamePartBuilder;



@interface OWSFingerprintProtosOwsfingerprintProtosRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FingerprintData_publicKey @"publicKey"
#define FingerprintData_identifier @"identifier"
@interface OWSFingerprintProtosFingerprintData : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPublicKey_:1;
  BOOL hasIdentifier_:1;
  NSData* publicKey;
  NSData* identifier;
}
- (BOOL) hasPublicKey;
- (BOOL) hasIdentifier;
@property (readonly, strong) NSData* publicKey;
@property (readonly, strong) NSData* identifier;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OWSFingerprintProtosFingerprintDataBuilder*) builder;
+ (OWSFingerprintProtosFingerprintDataBuilder*) builder;
+ (OWSFingerprintProtosFingerprintDataBuilder*) builderWithPrototype:(OWSFingerprintProtosFingerprintData*) prototype;
- (OWSFingerprintProtosFingerprintDataBuilder*) toBuilder;

+ (OWSFingerprintProtosFingerprintData*) parseFromData:(NSData*) data;
+ (OWSFingerprintProtosFingerprintData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OWSFingerprintProtosFingerprintData*) parseFromInputStream:(NSInputStream*) input;
+ (OWSFingerprintProtosFingerprintData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OWSFingerprintProtosFingerprintData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OWSFingerprintProtosFingerprintData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OWSFingerprintProtosFingerprintDataBuilder : PBGeneratedMessageBuilder {
@private
  OWSFingerprintProtosFingerprintData* resultFingerprintData;
}

- (OWSFingerprintProtosFingerprintData*) defaultInstance;

- (OWSFingerprintProtosFingerprintDataBuilder*) clear;
- (OWSFingerprintProtosFingerprintDataBuilder*) clone;

- (OWSFingerprintProtosFingerprintData*) build;
- (OWSFingerprintProtosFingerprintData*) buildPartial;

- (OWSFingerprintProtosFingerprintDataBuilder*) mergeFrom:(OWSFingerprintProtosFingerprintData*) other;
- (OWSFingerprintProtosFingerprintDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OWSFingerprintProtosFingerprintDataBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPublicKey;
- (NSData*) publicKey;
- (OWSFingerprintProtosFingerprintDataBuilder*) setPublicKey:(NSData*) value;
- (OWSFingerprintProtosFingerprintDataBuilder*) clearPublicKey;

- (BOOL) hasIdentifier;
- (NSData*) identifier;
- (OWSFingerprintProtosFingerprintDataBuilder*) setIdentifier:(NSData*) value;
- (OWSFingerprintProtosFingerprintDataBuilder*) clearIdentifier;
@end

#define CombinedFingerprint_version @"version"
#define CombinedFingerprint_localFingerprint @"localFingerprint"
#define CombinedFingerprint_remoteFingerprint @"remoteFingerprint"
@interface OWSFingerprintProtosCombinedFingerprint : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLocalFingerprint_:1;
  BOOL hasRemoteFingerprint_:1;
  BOOL hasVersion_:1;
  OWSFingerprintProtosFingerprintData* localFingerprint;
  OWSFingerprintProtosFingerprintData* remoteFingerprint;
  UInt32 version;
}
- (BOOL) hasVersion;
- (BOOL) hasLocalFingerprint;
- (BOOL) hasRemoteFingerprint;
@property (readonly) UInt32 version;
@property (readonly, strong) OWSFingerprintProtosFingerprintData* localFingerprint;
@property (readonly, strong) OWSFingerprintProtosFingerprintData* remoteFingerprint;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) builder;
+ (OWSFingerprintProtosCombinedFingerprintBuilder*) builder;
+ (OWSFingerprintProtosCombinedFingerprintBuilder*) builderWithPrototype:(OWSFingerprintProtosCombinedFingerprint*) prototype;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) toBuilder;

+ (OWSFingerprintProtosCombinedFingerprint*) parseFromData:(NSData*) data;
+ (OWSFingerprintProtosCombinedFingerprint*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OWSFingerprintProtosCombinedFingerprint*) parseFromInputStream:(NSInputStream*) input;
+ (OWSFingerprintProtosCombinedFingerprint*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OWSFingerprintProtosCombinedFingerprint*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OWSFingerprintProtosCombinedFingerprint*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OWSFingerprintProtosCombinedFingerprintBuilder : PBGeneratedMessageBuilder {
@private
  OWSFingerprintProtosCombinedFingerprint* resultCombinedFingerprint;
}

- (OWSFingerprintProtosCombinedFingerprint*) defaultInstance;

- (OWSFingerprintProtosCombinedFingerprintBuilder*) clear;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) clone;

- (OWSFingerprintProtosCombinedFingerprint*) build;
- (OWSFingerprintProtosCombinedFingerprint*) buildPartial;

- (OWSFingerprintProtosCombinedFingerprintBuilder*) mergeFrom:(OWSFingerprintProtosCombinedFingerprint*) other;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (UInt32) version;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) setVersion:(UInt32) value;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) clearVersion;

- (BOOL) hasLocalFingerprint;
- (OWSFingerprintProtosFingerprintData*) localFingerprint;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) setLocalFingerprint:(OWSFingerprintProtosFingerprintData*) value;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) setLocalFingerprintBuilder:(OWSFingerprintProtosFingerprintDataBuilder*) builderForValue;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) mergeLocalFingerprint:(OWSFingerprintProtosFingerprintData*) value;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) clearLocalFingerprint;

- (BOOL) hasRemoteFingerprint;
- (OWSFingerprintProtosFingerprintData*) remoteFingerprint;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) setRemoteFingerprint:(OWSFingerprintProtosFingerprintData*) value;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) setRemoteFingerprintBuilder:(OWSFingerprintProtosFingerprintDataBuilder*) builderForValue;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) mergeRemoteFingerprint:(OWSFingerprintProtosFingerprintData*) value;
- (OWSFingerprintProtosCombinedFingerprintBuilder*) clearRemoteFingerprint;
@end


// @@protoc_insertion_point(global_scope)
