#!/usr/bin/env bash

set -x
set -e

BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

REPO_ROOT=$BIN_DIR/../..
cd $REPO_ROOT

swift run --package-path Scripts/translation-tool translation-tool upload-resources

