#!/usr/bin/env bash
set -x
set -e

BIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

REPO_ROOT=$BIN_DIR/../..
LOCALIZATION_ROOT=$REPO_ROOT/Signal/translations
cd $LOCALIZATION_ROOT

cat <<EOS

Begin Pushing translation source
################################

EOS

$BIN_DIR/push-translation-source

cat <<EOS

Done Pushing translation source
###############################
Begin Pulling translations

EOS


$BIN_DIR/pull-translations
cat <<EOS

Done Pulling translations
#########################

EOS


